 import { getLeagueStandings } from './helperFunctions/leagueStandings';
+import { getLegacyHistory } from './helperFunctions/legacyHistory';  // ← add this

 export {
   enableBlog,
   homepageText,
   gotoManager,
   managers,
   getLeagueData,
   getLeagueTransactions,
   getNflState, 
   getLeagueRosters,
   getLeagueTeamManagers,
   getLeagueMatchups,
   getRivalryMatchups,
   getNews,
   loadPlayers,
   waitForAll,
   getUpcomingDraft,
   getPreviousDrafts,
   getLeagueRecords,
   cleanName,
   round,
   dues,
   leagueID,
   leagueName,
   dynasty,
   getAwards,
   stringDate,
   getBrackets,
   generateGraph,
   getBlogPosts,
   generateParagraph,
   predictScores,
   getLeagueStandings,
   getAuthor,
   parseDate,
   getAvatar,
   getTeamFromTeamManagers,
+  getLegacyHistory,   // ← add this
 }